### ISSUE TITLE
Dot '.' is illegal as a character of a MongoDB key

### ISSUE THREAD

**Issue by hampos** [KinkyDesign/JaqpotQuattro#24]
This creates the problem of storing URIs as keys in MongoDB.

**Comment by alphaville** [comment]
Let's take a look at this: http://stackoverflow.com/questions/8429318/how-to-use-dot-in-field-name

**Comment by alphaville** [comment]
I guess [this](http://www.baeldung.com/jackson-custom-serialization) is what we are looking for. I checked out [this answer](http://stackoverflow.com/a/16571347/613016), but the guy does something very tricky and uses `\uff0e` to escape periods, but if you notice closely `\uff0e` corresponds to a [fullwidth full stop](http://www.fileformat.info/info/unicode/char/ff0e/index.htm), i.e., not a standard period in a URI.

**Comment by hampos** [comment]
I think the idea of replacing '.' with '[DOT]' is the best one so far. We should make a JSONSerializer implementation that has a specific annotation that speaks only with MongoDB. That serializer should do this job, so when we retrieve our POJOs from the database they should already by fixed.

**Comment by hampos** [comment]
Fixed with custom JsonSerializer/DeSerializer for DataEntry class.
See https://github.com/KinkyDesign/JaqpotQuattro/commit/34b78bbdf4147fb8344e17c8c5c76a97e1abb624
