### ISSUE TITLE
Fix TaskHandler#init() - persist won't overwrite existing documents

### ISSUE THREAD

**Issue by alphaville** [KinkyDesign/JaqpotQuattro#3]
We need to implement a method that overwrites an entity when it exists or creates it. There must be a counterpart of the mongodb command `.save()` java-side.

Check out http://stackoverflow.com/questions/11717660/mongodb-java-api-difference-between-com-mongodb-dbcollection-save-and-com-mon for a potential solution to this problem.

**Comment by hampos** [comment]
MongoDB driver v3 does not support save() functionality.
I also believe this functionality is not needed. JaqpotEntityManager.persist() method will work only if the entity id is not used, similar to JPA's EntityManager.persist().
If the entity already exists, JaqpotEntityManager.merge() should be used instead.
