### ISSUE TITLE
Retrieving a dataset list from the database should return datasets the current user created.

### ISSUE THREAD

**Issue by hampos** [KinkyDesign/JaqpotQuattro#30]
A creator field should be placed in the meta of each dataset. The findAll query for datasets should return only datasets the requester has created and not everything in the database.

**Comment by alphaville** [comment]
True, but why not do it as in the case of Models and Algorithms. We can have a field called `createdBy`.

**Comment by hampos** [comment]
I don't see any implementation for the createdBy field. I believe it's ignored by the resource. Maybe an abstract implementation on AbstractHandler that finds entities of the same type belonging to a specific user should be made?

**Comment by hampos** [comment]
Whatever the case, getting all models, datasets, algorithms should be prohibited. A user should not be able to even get the URIs of the resources that they don't have permission to access.
We should think about how we could handle this issue. Getting a huge list of models only to find out that hey can only access a few would be frustrating for a user.
