### ISSUE TITLE
Create utils for AAA

### ISSUE THREAD

**Issue by alphaville** [KinkyDesign/JaqpotQuattro#5]
Create some utilities for AAA (Authentication, Authorisation, Accounting):

* In `UserResource` there is currently some application login which we can move to some utility classes.
* We can have some class, say `AA`, with which we login users, e.g., `AA.login(String username, String password)` returns `AuthToken`
* We need more functionality: To logout, check whether a user (identified by their `AuthToken`) can apply a method to a URI,
* Get public user information from SSO (email, name, etc) to create local accounts
* Get quota-related information on Jaqpot

Then, we can easily throw some exceptions for users that are not authenticated/authorized or have exceeded their quota and eventually handle them with Exception Mappers!

**Comment by hampos** [comment]
Create a `@Stateless` EJB named AAService in `org.jaqpot.core.services.data` and put all AA functionality there. Other EJBs can be injected in that bean, for example a UserHandler EJB that operates on User Entities in Mongo.

**Comment by alphaville** [comment]
Done!
