### ISSUE TITLE
Defining algorithm parameters on POST /algorithm

### ISSUE THREAD

**Issue by alphaville** [KinkyDesign/JaqpotQuattro#6]
When creating an algorithm (using `POST /algorithm`), we need to specify a list of parameters. For each parameter of course, we need to specify their scope (optional/mandatory), default value, parameter type (nominal/numeric/etc), name and possibly some meta-data. Therefore, I think parameters should be POSTed in JSON format and not as:

`@FormParam("parameters") String parameters`

But as 

`List<Parameter> parameters`

What do you think?

**Comment by hampos** [comment]
Yes I totally agree. A JSON containing all information about parameters including their default values would be the best solution. We must agree though on the way of providing those parameters for training as well.

**Comment by alphaville** [comment]
resolved!
