### ISSUE TITLE
EAR Redeployment on Wildfly

### ISSUE THREAD

**Issue by hampos** [KinkyDesign/JaqpotQuattro#7]
Redeploying Jaqpot's EAR module to Wildfly seems unstable and takes too long. In the logs one can observe that the redeployment happens more than 2-3 consecutive tmes before it stabilises. 
This could be related to our maven configurations.

**Comment by hampos** [comment]
I tested deploying the EAR from wildfly's web console. Doing it this way works absolutely fine and deploys in 2-3 seconds. Maybe this is an issue of Netbeans after all?

**Comment by alphaville** [comment]
How did you do that? Can you briefly outline the steps?

**Comment by hampos** [comment]
I just went to http://localhost:9990/console/App.html#home on Deployments menu, selected JaqpotEAR and clicked Replace. Then in the file popup I chose the .ear file from JaqpotEAR module's target folder, and the redeployment happened in seconds.

**Comment by alphaville** [comment]
I believe it seems it takes only 2s, but it takes more time to really deploy it. If you try `mvn wildfly:redeploy` (you need to add the wildfly mvn plugin) it takes 11.0s.

**Comment by alphaville** [comment]
This is how I am currently dealing with this issue: to build jaqpot for the remote server, I use the following script (`remote_jbuild.sh`):

```
JAVA_HOME=/usr/lib/jvm/java-8-oracle 
mvn -DskipTests=true -P JaqpotQuattroENM install
```

and then to deploy the application, I `scp` the target .ear file to the remote deployment folder, that is (remote_deploy.sh):

```
scp JaqpotEAR/target/JaqpotEAR-1.0-SNAPSHOT.ear \
   enanomapper.ntua.gr:/opt/wildfly/standalone/deployments
``` 

clean is as simple as (klean.sh):

```
JAVA_HOME=/usr/lib/jvm/java-8-oracle
mvn -DskipTests=true clean
```

while, when I need to build Jaqpot for local deployment I use (jbuild.sh):

```
JAVA_HOME=/usr/lib/jvm/java-8-oracle 
mvn -DskipTests=true -P JaqpotQuattroLocal install
```

redeployment on the remote machine is quite fast (about 10 seconds). This is how I build and deploy so far [Netbeans gives me some trouble every now and then, so I decided to do everything this way]. We need however to create mvn targets to automate the above procedure.
